### ISSUE TITLE
DeprecationWarning upon "import holidays" in version 0.17

### ISSUE THREAD

**Issue by walkerh** [dr-prodigy/python-holidays#793] opened 2022-11-14 20:40 UTC
The implementation of deprecating the Swaziland calendar contains a bug. Just importing the holidays package is enough to fire the `DeprecationWarning`.

**Steps to reproduce (in bash):**

```bash
# Setup
python -m venv demo
source demo/bin/activate
pip install --upgrade pip

# Bad version
pip install holidays==0.17

# Expose bug
python -W error::DeprecationWarning -c 'import holidays'

# Workoround
pip uninstall -y holidays
pip install holidays!=0.17
python -W error::DeprecationWarning -c 'import holidays'

# Cleanup
deactivate
rm -rf demo
```

**Expected behavior:**

The `DeprecationWarning` should only fire when the user constructs an instance of the `Swaziland` or a subclass.

**Comment by arkid15r** [comment] 2022-11-14 23:20
HI @walkerh,
thanks for the detailed issue explanation!

My understanding is that the root cause of the problem is not the deprecation warning itself but the way you're treating them with `-W error::DeprecationWarning` options. What is your use-case for turning the warning into an exception?

While I can help "fixing" the issue in this particular case with `Swaziland` there is no guarantee that another warning won't arise in next python-holidays version. The class level warning can be fixed by wrapping it to a constructor method. With module level deprecation warnings there wouldn't be such a workaround possible.

I'm working on a PR to fix the reported issue for now.

**Comment by walkerh** [comment] 2022-11-15 19:27
The `-W error::DeprecationWarning` flag was a simple way of demonstrating the problem. I first became aware of this issue when updating `holidays` cause my `pytest` output to start emitting these warnings. I could have just suppressed the warnings, but that just hides the real problem.

Thanks for getting on this.

**Comment by arkid15r** [comment] 2022-11-16 00:58
Got it, thanks for the explanation @walkerh!

I agree that in this particular case the warning could be fired in a more sophisticated way (#794 PR filed). However, as I  understand the concept, a warning itself is not a problem but an intentionally shown piece of information notifying the end users about upcoming changes.

Please let me know if you have any suggestions regarding the way you'd prefer to work with the deprecation warnings in the future.

Thank you!

**Comment by walkerh** [comment] 2022-11-16 16:57
My suggestion is to implement a constructor for `Swaziland` that:

1. emits the warning
2. invokes `super(*args, **kwargs)`

Then the warning will only show up when someone actually invokes `Swaziland()`. The vast, vast majority of users of this package have never and will never use the deprecated Swaziland calendar. They shouldn't have to see this deprecation warning just because they run pytest.

**Comment by arkid15r** [comment] 2022-11-16 17:01
The suggested fix was implemented in #794 PR yesterday.

Thank you!

**Comment by aberres** [comment] 2022-11-17 08:46
> What is your use-case for turning the warning into an exception?

Another answer to this question: Our CI runs with `-W error::DeprecationWarning` to allow us to spot any upcoming issues early. We then either fix the warning right away or explicitly ignore it.

Thanks for fixing it!

**Comment by anentropic** [comment] 2022-11-23 11:25
> Another answer to this question: Our CI runs with `-W error::DeprecationWarning` to allow us to spot any upcoming issues early. We then either fix the warning right away or explicitly ignore it.

Same here

**Comment by dr-prodigy** [comment] 2022-11-23 23:02
Unfortunately I could not work on a new release for some days.. now it's online and should be okay. Thx!

**Closed by dr-prodigy** 2022-11-23 23:02 UTC
