### ISSUE TITLE
Malaysia Holidays

### ISSUE THREAD

**Issue by mrkgoh** [dr-prodigy/python-holidays#466] opened 2021-05-13 19:10 UTC
Kindly request that Malaysia's holidays are added

**Comment by dr-prodigy** [comment] 2021-05-14 08:35
Hi,
as this is a community-fueled open source project, we don't develop new features on request.. but if you would like to do it, we will surely support you in it.. 
Any contribution is welcome!

Thx,
dr-p

**Comment by mrkgoh** [comment] 2021-05-27 14:47
Malaysia's holiday is similar to Singapore's. I am new to github, any advice how to I start malaysia.py from singapore.py? Would like to do my part. Any guidance is appreciated.

**Comment by jusce17** [comment] 2021-06-10 08:10
@dr-prodigy  I can work on this one 😊 

@mrkgoh, if you could be so kind in listing me Malaysian holidays would be amazing, I have done some research (just a quick one) and it looks like you guys have a lot of holidays

**Comment by mrkgoh** [comment] 2021-06-11 03:29
@jusce17 , thanks looking forward to learning from you.

I hacked a quick code that you can use to scrape the holidays for Malaysia from http://www.officeholidays.com/countries/malaysia/

It takes year range from 2018 to 2024 and output a 'MYholiday.csv'

```
  import requests
  import pandas as pd
  
  hol = pd.DataFrame()
  
  for year in range(2018, 2024):
  
      url = f'http://www.officeholidays.com/countries/malaysia/{str(year)}'
      
      header = 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'
      
      with requests.get(url, headers={'User-Agent': header}, verify=False) as req:
          if req.status_code==200:
              sauce = req.content
              print('{:<47s} : {}'.format('Grab html','Done'))
          else:
              print('{:<47s} : {}'.format('Grab html',req.status_code))
      
      df = pd.read_html(sauce, header=0)[0]
      df.loc[:,'Date'] = [i + f' {str(year)}' for i in df.loc[:,'Date']]
      
      hol = pd.concat([hol, df], ignore_index = True)
      
  hol.to_csv('MYholiday.csv')

```

**Comment by mborsetti** [comment] 2021-06-11 09:40
@jusce17  Thanks for leading the effort! I authored the code for Singapore, which is probably the closest one to clone (Singapore used to be a province of Malaysia until 1965); feel free to reach out for help.

@mrkgoh Thanks for the info, but what is needed is the *rules* for the holidays, preferably official ones, so they can be coded, and holidays can be _generated_ annually.  For Singapore I was able to find the [Holidays Act](https://sso.agc.gov.sg/Act/HA1998), which spells out that the day of some Muslim holidays are confirmed annually by the Ministry of Manpower, who publishes them [here](https://www.mom.gov.sg/employment-practices/public-holidays), so was able to code an algorithmic baseline (with guesstimates for Muslim holidays based on the lunar calendar) which gets updated manually annually when the Ministry confirms the exact date of such holidays.   Can you provide similar references for Malaysia (Google Translate works for laws in Malay)?

**Comment by mrkgoh** [comment] 2021-06-11 14:22
@mborsetti , thanks. Looking forward to learning from you.

1. For Malaysia, we comply to Holiday Act 1951 [Act 369]. English [link.](https://www.lawyerment.com/library/legislation/acts/1951/369/) PDF [version](https://www.lawyerment.com/library/legislation/acts/1951/369/). So no need to translate here.
2.  Yes the government do publishes in Malay only at the following [link](https://www.malaysia.gov.my/portal/content/147). 
3.  Yes you are right. The muslim holiday is confirm annually.

**Comment by jusce17** [comment] 2021-07-04 02:11
Sorry @mrkgoh @mborsetti,  I have been very busy with work and didn't have much time to look into it, turns out Malaysia holidays are a bit harder than I expected, unlike Singapore it does have different states with their own regionals holidays, 

I create the pull request #481 were you guys can take look. @mrkgoh it would be nice if you could double check the holidays, I founded a bit hard to understand them all.

@mborsetti since it was basically a copy of the Singapore one, perhaps you could take a look too. I wasn't able to add those holidays that follow the Islamic calendar, perhaps you can help with it ?


It was actually quite interesting to make this small contribution, I spent most of the time studying the regions and history of Malaysian than actually coding 😅😅

**Comment by mborsetti** [comment] 2021-07-06 02:50
Hi @jusce17, nice work, and yeah quite a lot of regional holidays!

I will look into the Islamic holidays over this coming weekend and should be able to contribute a similar algorithmic baseline to the one I used for Singapore.

**Comment by dr-prodigy** [comment] 2021-09-18 21:03
Hi everyone, the first implementation of Malaysian holidays, although not referenced in CHANGES file, has been added on v0.11.2.
Therefore, I fixed CHANGES accordingly and I close this issue (issues cleanup).
I ask you to please start a new PR in case you work on its improved version (islamic holidays).
Thank you both, best 👍

**Closed by dr-prodigy** 2021-09-18 21:03 UTC
Labels: enhancement, help wanted
