### ISSUE TITLE
Countrycode LI for Liechtenstein not working in HA

### ISSUE THREAD

**Issue by MartinR80** [dr-prodigy/python-holidays#808] opened 2022-11-27 11:33 UTC
When i put in the Countrycode for Liechtenstein "LI" Home Assistant says the configuration is not valid.

"Invalid config for [binary_sensor.workday]: Country is not supported. for dictionary value @ data['country']. Got 'LI'. (See ?, line ?). "

If i change it to Switzerland (CH) or Germany (DE) it is valid and works.

**Comment by dr-prodigy** [comment] 2022-11-27 12:51
Hi @MartinR80 ,
unfortunately this doesn't seem to be related to python_holidays, as you can check from here:

```
>>> import holidays
>>> import datetime
>>> x = holidays.country_holidays('LI')
>>> x
holidays.country_holidays('LI')
>>> datetime.date(2022,1,1) in x
True
>>> x
{datetime.date(2022, 1, 1): 'Neujahr', datetime.date(2022, 1, 2): 'Berchtoldstag', datetime.date(2022, 1, 6): 'Drei Könige', datetime.date(2022, 2, 2): 'Mariä Lichtmess', datetime.date(2022, 3, 1): 'Fasnachtsdienstag', datetime.date(2022, 3, 19): 'Josefstag', datetime.date(2022, 4, 15): 'Karfreitag', datetime.date(2022, 4, 17): 'Ostersonntag', datetime.date(2022, 4, 18): 'Ostermontag', datetime.date(2022, 5, 1): 'Tag der Arbeit', datetime.date(2022, 5, 26): 'Auffahrt', datetime.date(2022, 6, 5): 'Pfingstsonntag', datetime.date(2022, 6, 6): 'Pfingstmontag', datetime.date(2022, 6, 16): 'Fronleichnam', datetime.date(2022, 8, 15): 'Staatsfeiertag', datetime.date(2022, 9, 8): 'Maria Geburt', datetime.date(2022, 11, 1): 'Allerheiligen', datetime.date(2022, 12, 8): 'Maria Empfängnis', datetime.date(2022, 12, 24): 'Heiliger Abend', datetime.date(2022, 12, 25): 'Weihnachten', datetime.date(2022, 12, 26): 'Stefanstag', datetime.date(2022, 12, 31): 'Silvester'}
>>> x = holidays.LI()
>>> datetime.date(2022,1,1) in x
True
>>> x
{datetime.date(2022, 1, 1): 'Neujahr', datetime.date(2022, 1, 2): 'Berchtoldstag', datetime.date(2022, 1, 6): 'Drei Könige', datetime.date(2022, 2, 2): 'Mariä Lichtmess', datetime.date(2022, 3, 1): 'Fasnachtsdienstag', datetime.date(2022, 3, 19): 'Josefstag', datetime.date(2022, 4, 15): 'Karfreitag', datetime.date(2022, 4, 17): 'Ostersonntag', datetime.date(2022, 4, 18): 'Ostermontag', datetime.date(2022, 5, 1): 'Tag der Arbeit', datetime.date(2022, 5, 26): 'Auffahrt', datetime.date(2022, 6, 5): 'Pfingstsonntag', datetime.date(2022, 6, 6): 'Pfingstmontag', datetime.date(2022, 6, 16): 'Fronleichnam', datetime.date(2022, 8, 15): 'Staatsfeiertag', datetime.date(2022, 9, 8): 'Maria Geburt', datetime.date(2022, 11, 1): 'Allerheiligen', datetime.date(2022, 12, 8): 'Maria Empfängnis', datetime.date(2022, 12, 24): 'Heiliger Abend', datetime.date(2022, 12, 25): 'Weihnachten', datetime.date(2022, 12, 26): 'Stefanstag', datetime.date(2022, 12, 31): 'Silvester'}
>>> x = holidays.Liechtenstein()
>>> datetime.date(2022,1,1) in x
True
>>> x
{datetime.date(2022, 1, 1): 'Neujahr', datetime.date(2022, 1, 2): 'Berchtoldstag', datetime.date(2022, 1, 6): 'Drei Könige', datetime.date(2022, 2, 2): 'Mariä Lichtmess', datetime.date(2022, 3, 1): 'Fasnachtsdienstag', datetime.date(2022, 3, 19): 'Josefstag', datetime.date(2022, 4, 15): 'Karfreitag', datetime.date(2022, 4, 17): 'Ostersonntag', datetime.date(2022, 4, 18): 'Ostermontag', datetime.date(2022, 5, 1): 'Tag der Arbeit', datetime.date(2022, 5, 26): 'Auffahrt', datetime.date(2022, 6, 5): 'Pfingstsonntag', datetime.date(2022, 6, 6): 'Pfingstmontag', datetime.date(2022, 6, 16): 'Fronleichnam', datetime.date(2022, 8, 15): 'Staatsfeiertag', datetime.date(2022, 9, 8): 'Maria Geburt', datetime.date(2022, 11, 1): 'Allerheiligen', datetime.date(2022, 12, 8): 'Maria Empfängnis', datetime.date(2022, 12, 24): 'Heiliger Abend', datetime.date(2022, 12, 25): 'Weihnachten', datetime.date(2022, 12, 26): 'Stefanstag', datetime.date(2022, 12, 31): 'Silvester'}
```

No clues about why it is not working for you, but in case you have no other evidences to shed light on a possible issue on python_holidays side, I suggest you to report this to the Home Assistant project.

Good luck 👍

**Comment by MartinR80** [comment] 2022-11-27 13:16
Thanks for your quick replay and the info. Ill check with HA then.

**Comment by arkid15r** [comment] 2022-11-27 17:06
> Thanks for your quick replay and the info. Ill check with HA then.

Hey @MartinR80,
It does look like an HA issue so far. The LI support was added not very long time ago. Could be just an old version issue. I'll add more details later after looking into it.

**Comment by arkid15r** [comment] 2022-11-27 18:35
The issue should be fixed in HA soon - https://github.com/home-assistant/core/pull/82799.

**Comment by dr-prodigy** [comment] 2022-11-27 21:57
Yep.. caused by outdated (0.16) holidays dependency. 
@MartinR80 even if HA is probably about to release a fix for this, you still can manually upgrade holidays yourself to the latest version (0.17) to get support for Liechtenstein prior to that fix.
This said I'm closing this.. cheers everyone 👍

**Closed by dr-prodigy** 2022-11-27 21:57 UTC
