### ISSUE TITLE
Using slice to get holidays between two dates only returns holidays from the start year and the end year

### ISSUE THREAD

**Issue by justinwaf** [dr-prodigy/python-holidays#529] opened 2021-09-29 16:21 UTC
STEPS TO REPRODUCE
1. Aim: retrieve list of all holidays between 2014-12-31 and 2016-01-01
```
us_holidays = holidays.US()
us_holidays['2014-12-31': '2016-01-01']
```

EXPECTED BEHAVIOUR
1. Retuns a list of all holidays in 2015 plus 1st January 2016

OBSERVED BEHAVIOUR
1. Returns `[datetime.date(2016, 1, 1)]`

**Comment by dr-prodigy** [comment] 2021-09-29 21:20
Hi,
to be honest, in the provided example the 2 dates - written as strings - don't seem suitable for a python "slicing", and therefore are considered as 2 elements.

Then, the library works as expected / documented, ie: collecting holidays for the years of all the provided dates (2014, 2016), so 
```
import holidays
us_holidays = holidays.US()
us_holidays['2014-12-31': '2016-01-01']
us_holidays
```
correctly shows holidays for both 2014 and 2016.

Available for further clarifications, thx!

**Comment by mborsetti** [comment] 2021-09-29 23:42
@dr-prodigy 

I took a look at the original code and it does seem to be set up for accepting slicing of two dates, as per the code below in `__getitem__` (the call to `__keytransform__` allows the keys to be in any of the supported formats, including an ISO 8601 string):

https://github.com/dr-prodigy/python-holidays/blob/5cde25b7e2e15578c7c1ab6e3f1a7ebda444fd80/holidays/holiday_base.py#L241-L274

However, I don't think that the recursive call to `dict.__getitem__(self, day)` in line 270 gets to expand (load) the dates, but calling `self.__getitem__(day)` instead does.  

So it's basically a one-line fix that I will submit as a PR.

**Comment by mborsetti** [comment] 2021-09-29 23:48
@justinwaf 

Thanks for taking the time to report this.

> EXPECTED BEHAVIOUR
> 
> 1. Returns a list of all holidays in 2015 plus 1st January 2016

I just want to clarify that the expected behavior is incorrect: in Python, slicing is done with half-open intervals and upper bounds are exclusive . See https://stackoverflow.com/questions/11364533/why-are-slice-and-range-upper-bound-exclusive

Once the fix is in, the behavior is to return 2014-12-31 if it were a holiday (it isn't so it won't) and all holidays for 2015, but **not** return 2016-01-01.

**Comment by justinwaf** [comment] 2021-09-30 06:53
> Hi, I hope I'm not mistaking but, to be honest, in the provided example the 2 dates - written as strings - don't seem suitable for a python "slicing", and therefore are considered as 2 elements.
> 
> Then, the library works as expected / documented, ie: collecting holidays for the years of all the provided dates (2014, 2016), so
> 
> ```
> import holidays
> us_holidays = holidays.US()
> us_holidays['2014-12-31': '2016-01-01']
> us_holidays
> ```
> 
> correctly shows holidays for both 2014 and 2016.
> 
> Please let me know if I didn't catch it right, I'm available for further clarifications.. thx!

The example I used was a slightly expanded one I got from the README.rst
us_holidays['2014-01-01': '2014-01-03']  # [date(2014, 1, 1)]

From this example I understood that you could send in 2 dates as strings and get back a list of all the holidays in between (and not including the end date).  What I observed is I only got holidays for the year of the first date, and the year of the last date, and the years in between were skipped.

**Comment by dr-prodigy** [comment] 2021-11-27 09:33
Hi @justinwaf and @mborsetti 
thank you both for your support!

After a further analisys on your points (sorry for not understanding them in first place), I confirm you are both right.
The issue was probably buried in the code since before I started working on the lib, so good shot!

I noticed the PR made by Mike has been closed, so I re-applied it (one row fix, quickwin! :-) ) in a new commit.

Thank you both again, KUTGW! 👍

**Closed by dr-prodigy** 2021-11-27 09:33 UTC
