### ISSUE TITLE
upgrade "convertdate" to >= 2.3.0

### ISSUE THREAD

**Issue by mehditerraneen** [dr-prodigy/python-holidays#406] opened 2020-12-08 08:33 UTC
Hi, Is it possible to check if upgrading to convertdate version >=2.3.0 does not have a big impact ?
Thanks

**Comment by MartinLinden** [comment] 2020-12-09 15:32
Hi! Great package, thanks for that. I would very much support an update on convertdate. The current version limits pytz to be < 2020 which makes the library run into dependency problems with other libraries

**Comment by zhaoyongjie** [comment] 2020-12-11 02:16
Awesome library for holiday searching. but current pytz < 2020 conflict with many current popular libraries.

**Comment by fabaff** [comment] 2020-12-14 11:54
`convertdate<=2.2.0` is an issue for the Fedora package.

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1905176

**Comment by ondrejj** [comment] 2020-12-28 10:32
According to convertdate changes (https://github.com/fitnr/convertdate/releases/tag/v2.3.0) there are no changes, which should affect holidays.
Why there is version requirement for convertdate<=2.2?

**Comment by lociii** [comment] 2021-01-15 16:39
Limitation introduced in b57cb2dd3d3c2a1f16f8f04f89ab3762feba930c by @mmontel-wgs and released in 0.10.4 - 0.10.3 is not affected.
Maybe he can give an explanation.

**Comment by dr-prodigy** [comment] 2021-01-31 00:21
The limitation has in fact been introduced due to convertdate 2.2.0 breaking changes (most notable one: support for Python 2 dropped, some method signature changes, etc.), which prevented us to accept it immediately.
I decided (mmontel-wgs is my 2nd account) to release a last Python 2 compatible version (0.10.4), to remove this limit in the upcoming, now in beta, version. This of course required a "keep-back" for convertdate.

Pls refer to https://github.com/dr-prodigy/python-holidays#development-version for how to change your holidays lib to beta version until it gets finalized and released in master, thx.

**Comment by lociii** [comment] 2021-01-31 13:35
@dr-prodigy Thanks for the explanation. Do you have any ETA on the next release?

**Comment by dr-prodigy** [comment] 2021-02-01 08:59
hi @lociii in fact, no, I don't have set a date yet: usually I sum up a reasonable number of updates before releasing: in the meantime, for who needs bleeding edge updates, the beta branch is the way to go (no untested / unstable features on it, never).
https://github.com/dr-prodigy/python-holidays#development-version
Does this suit your needs?
Pls let me know, thx

**Comment by lociii** [comment] 2021-02-03 14:10
That might work for an end user but not for a package depending on python-holidays.
I'd deeply recommend releasing a new version even if you haven't accumulated too many changes as the pytz < 2020 might be blocking some important updates on other packages.

**Comment by mweinelt** [comment] 2021-02-03 18:31
We are having the same problem in NixOS packaging sadly. Please release a version supporting recent convertdate versions.

**Comment by dr-prodigy** [comment] 2021-02-03 21:55
Hi,
I confirm I've just released v0.10.5 on master and pypi to solve the issues: please keep me posted on your status.
Thank you all for your interest and support.

**Comment by mweinelt** [comment] 2021-02-03 22:04
Thanks! One issue came up: `hijri_converter` is missing in the list of dependencies.

**Comment by dr-prodigy** [comment] 2021-02-03 23:45
Hi,
it should be fixed now and released as 0.10.5.1 on pypi.
Pls let me know, thank you very much!

**Comment by dr-prodigy** [comment] 2021-02-04 07:23
Confirmed as fixed on other similar issue. Closing, thx 👍

**Closed by dr-prodigy** 2021-02-04 07:23 UTC
