### ISSUE TITLE
Ireland considering UK as base class and hence not being a country itself

### ISSUE THREAD

**Issue by guinnberg** [dr-prodigy/python-holidays#636] opened 2022-03-03 14:29 UTC
Issue also opened here:
home-assistant/core#67542

Looks like Ireland is being considered as being part of the UK which is wrong as not all the holidays in the UK exist, or necessarily exist in Ireland.

Take a reference on this comment: https://github.com/home-assistant/core/issues/67542#issuecomment-1058079650

**Comment by javicalle** [comment] 2022-03-03 15:36
My comment goes in the original issue matter in HA forum, that Ireland seems not to be one of the `list_supported_countries`, but if you want to discuss other topic here just ignore my comment.

**Comment by guinnberg** [comment] 2022-03-03 15:47
I don't fully understand the last part, but yeah, basically the intended discussion here (at least for me) is to be able to use again Ireland as a country in Home Assistant, not interested in politics :)

Let me know if I should change something on the details so it's clearer.

**Comment by javicalle** [comment] 2022-03-03 16:19
IMHO the issue subject must reflect what the problem is.
The most info you can include (besides point to another place) will make easier to maintainers to understand the problem and can be easy to them to fix.

IMHO the actual redaction seems to argue about a different matter.

**Comment by guinnberg** [comment] 2022-03-03 16:37
Sure, sorry about that, I'll try to do my best, but as I mentioned in the other issue, I'm not fully aware of this library hence the ask for a recommendation of what to explain here... 

Feel free to suggest any other changes or whatever is needed to get this properly explained

**Comment by kenguest** [comment] 2022-03-04 10:17
I'd humbly suggest that you don't inherit the class for one country from another - perhaps you need to audit the codebase to ensure this problem isn't going to manifest for some other country class as well.
regardless of the political aspect of this - there are a lot of assumptions that things are going to match and that changes are only going to be additive etc etc
(I do have some experience of this as developer and maintainer of the pear/php equivalent -  https://pear.php.net/package/Date_Holidays )

**Comment by sotatech** [comment] 2022-03-07 08:54
Indeed, and the following is a good example of the dfferences:

17th March 2022 - St. Patricks's day Bank Holiday in Ireland and Northern Ireland only.
18th March 2022 - Day of Remembrance and Recognition Bank Holiday in Ireland only.

**Comment by dr-prodigy** [comment] 2022-04-02 17:31
Thanks to @TeoTN this is now fixed and released on beta.
Closing this, thx everyone 👍

**Closed by dr-prodigy** 2022-04-02 17:31 UTC

**Comment by kenguest** [comment] 2022-06-03 09:15
hi, just wondering when will this fix be in a "proper" (non-beta) release?
