### ISSUE TITLE
I found issue when import fbprophet when using holidays Library

### ISSUE THREAD

**Issue by hiennguyen15** [dr-prodigy/python-holidays#277] opened 2020-01-26 10:48 UTC
When I importing fbprophet version = 0.5 
and holidays version =0.10.1
I faced this issue. Can anyone help me?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-70-4f89f47c1bda> in <module>
----> 1 import fbprophet

/opt/anaconda3/lib/python3.7/site-packages/fbprophet/__init__.py in <module>
      6 # of patent rights can be found in the PATENTS file in the same directory.
      7 
----> 8 from fbprophet.forecaster import Prophet
      9 
     10 __version__ = '0.5'

/opt/anaconda3/lib/python3.7/site-packages/fbprophet/forecaster.py in <module>
     18 
     19 from fbprophet.diagnostics import prophet_copy
---> 20 from fbprophet.make_holidays import get_holiday_names, make_holidays_df
     21 from fbprophet.models import prophet_stan_model
     22 from fbprophet.plot import (plot, plot_components, plot_forecast_component,

/opt/anaconda3/lib/python3.7/site-packages/fbprophet/make_holidays.py in <module>
     14 import pandas as pd
     15 
---> 16 import fbprophet.hdays as hdays_part2
     17 import holidays as hdays_part1
     18 

/opt/anaconda3/lib/python3.7/site-packages/fbprophet/hdays.py in <module>
     14 
     15 from convertdate.islamic import from_gregorian, to_gregorian
---> 16 from holidays import WEEKEND, HolidayBase, easter, rd
     17 from lunardate import LunarDate
     18 

ImportError: cannot import name 'easter' from 'holidays' (/opt/anaconda3/lib/python3.7/site-packages/holidays/__init__.py)

**Comment by dr-prodigy** [comment] 2020-01-27 01:03
Hi,
"easter" is not a holidays function, but instead a dateutil library function.
Until the previous version of holidays (0.9.12) it was "accidentally" accessible, due to it being imported in holidays.py (main library module, now removed in favour of single country modules), but its direct reference made in prophet is basically wrong (same goes for WEEKEND, HolidayBase etc., not meant for being accessed from outside holidays library).

In order to fix fbprophet, replacing the erroring import with
> from dateutil.easter import easter

should be sufficient.
I will consider re-adding in a future the availability of "easter" to support cases like this even if, as said, this doesn't fall in the documented / official usages of holidays library.

**Comment by hiennguyen15** [comment] 2020-01-27 03:56
Thank man, I will try.

**Comment by Cgarr95** [comment] 2020-01-30 02:01
Hola,
soy nuevo en programación, me ha sucedido el mismo error que informan en esta consulta. Agradeceré me puedan orientar en el paso a paso de como reemplazar la importación con error del fbprophet.
saludos

**Comment by Cgarr95** [comment] 2020-01-30 02:02
Hola,
soy nuevo en programación y se ha generado el mismo error que informan en esta consulta, agradeceré  me puedan decir el paso a paso para reemplazar la importación  con error del fbprophet,
saludos

**Comment by gemammi** [comment] 2020-01-30 07:53
hey @dr-prodigy , after i did replace the easter from holidays to :

from dateutil.easter import easter

now i got this error:
ImportError: cannot import name 'rd' from 'holidays' (C:\Users\ASUS\Anaconda3\lib\site-packages\holidays\__init__.py)

and i have no idea the library that i can import rd from

**Comment by dr-prodigy** [comment] 2020-01-30 11:42
I don't know why these references have been implemented in fbprophet, but they're completely wrong..
This specifically seems to refer to this import line:
`
from dateutil.relativedelta import relativedelta as rd
`

(formerly reachable from outside, now not accessible anymore).
"rd" in the end is just an **internal reference** to dateutil.relativedelta (shortened to reduce code length), and therefore has NO SENSE outside holidays' code.

Given this (+ the previous issue about easter), I strongly suggest to open an issue / pull request for complete refactoring on fbprophet in order to fix these poor coding cases.

**Comment by dr-prodigy** [comment] 2020-01-30 12:01
PS: in order to avoid new issues opened on these cases, please keep this issue open. Thanks

**Comment by divinealpine** [comment] 2020-01-31 01:55
I'm following a Time Series Analysis tutorial that describes importing fbprophet. I have a single cell with this:

import fbprophet

the error I receive is ImportError: cannot import name 'easter'

---

![image](https://user-images.githubusercontent.com/7386822/73506181-a66d8f80-4389-11ea-97e1-09716ee586b4.png)

**Comment by arturgontijo** [comment] 2020-01-31 13:50
Replace line 16 in `fbprophet/hdays.py`:

```
from holidays import WEEKEND, HolidayBase, easter, rd
```
to
```
from holidays import WEEKEND, HolidayBase
from dateutil.easter import easter
from dateutil.relativedelta import relativedelta as rd
```

**Comment by dr-prodigy** [comment] 2020-02-01 07:19
Hi, this issue has been confirmed, fixed and released on github by fbprophet maintainers.
A new version of fbprophet will be soon released on PyPI. 
Complete info here:
https://github.com/facebook/prophet/issues/1293

Keeping this open to avoid new duplicated issue reports.

**Comment by RSwarnkar** [comment] 2020-02-03 15:18
Is this fixed? I am getting error while using it in docker.

**Comment by sschrier-coder** [comment] 2020-02-05 21:59
@dr-prodigy My colleague and I are running into the same above issue importing fbprophet, even though per note above, we had thought this was resolved. Can you please advise on the best fix?

**Comment by jkmutesi** [comment] 2020-02-16 11:00
@dr-prodigy , to temporarily fix this problem, one should import `easter` from `dateutil` using the line: from `dateutil.easter` import `easter`

After I have executed the line: `from dateutil.easter import easter`, how do I move from here and then use `fbprophet` ? I am using jupyter notebook.

```
Given my DataFrame, df,
m = Prophet(),
m.fit(df),
```

**Comment by dr-prodigy** [comment] 2020-02-21 21:03
Prophet's maintainers report the fix has been now pushed to PyPi / Conda, so there should be no more issues.
Please refer to here for details:
https://github.com/facebook/prophet/issues/1293#issuecomment-589832103

**Closed** 2020-02-24 21:17 UTC
Labels: wontfix

**Comment by niladri2909** [comment] 2021-08-28 19:41
I have installed fbprophet using `conda install -c conda-forge fbprophet -y `in my python 3.7 on windows 10.but `import fbprophet ` is throwing error `ImportError: cannot import name 'easter'` Can you suggest how to fix that issue?
