### ISSUE TITLE
Error being emitted by holidays==0.25

### ISSUE THREAD

**Issue by rdunlap-inspire11** [dr-prodigy/python-holidays#1188] opened 2023-05-15 18:26 UTC
Just had pytest tests in a pipeline start emitting an error culminating in:

../../anaconda3/envs/dp_env_new/lib/python3.8/site-packages/holidays/registry.py:178: in __init__
    super().__init__(*args, **kwargs)
E   TypeError: object.__init__() takes exactly one argument (the instance to initialize)

The error goes away if I force holidays==0.24 (holidays was being installed as a dependency of prophet==1.1).  The pipeline is using Python 3.8.

**Comment by arkid15r** [comment] 2023-05-15 19:32
Hi @rdunlap-inspire11,
thanks for reporting this.

Please see https://github.com/facebook/prophet/pull/2431

**Comment by kaegie** [comment] 2023-05-15 22:55
same issue is occurring with greykite import as well when running 
from greykite.framework.templates.forecaster import Forecaster

**Comment by arkid15r** [comment] 2023-05-18 02:53
The corresponding prophet [issue](https://github.com/facebook/prophet/issues/2430) has been resolved. 
Closing this.

> same issue is occurring with greykite import as well when running from greykite.framework.templates.forecaster import Forecaster

If the issue had been caused by prophet was also fixed (prophet v1.1.3)

**Closed by arkid15r** 2023-05-18 02:53 UTC
